config/routes.rb
Rails.application.routes.draw do
  get 'users/search'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :pictureboard, only: [:index]
  resources :posts, only: [:create] do 
  	collection do 
  		get :subscribed_posts
  	end
  end
  resources :follows, only:[:create, :destroy]
  root "pictureboard#index"
  # mount ImageUploader::UploadEndpoint => "/posts/images"
  mount ImageUploader.upload_endpoint(:cache) => "/images/upload"
  mount ImageUploader.upload_endpoint(:store) => "/images/upload_store"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  include ImageUploader[:image]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  acts_as_follower
  acts_as_followable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
    # before_action :authenticate_user!
  respond_to :js

  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user)
    respond_to do |format|
      format.js {}
    end
  end

  def destroy
    @user = User.find(params[:id])
    current_user.stop_following(@user)
    respond_to do |format|
      format.js {}
    end
  end
end

app/controllers/pictureboard_controller.rb
class PictureboardController < ApplicationController
  def index
    @post = Post.new
    @posts = current_user.posts
    @followed_users = current_user.all_following
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  helper_method :jsonize_post
  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      render json: { message: "success", fileID: @post.id  }, :status => 200
    else
      render json: { error: @post.errors.full_messages.join(',')}, :status => 400
    end     
  end

  def subscribed_posts
    data = []
    current_user.posts.each do |post|
      data << jsonize_post(post, current_user)
    end
    @all_subscribed_users = current_user.all_following
    @all_subscribed_users.each do |u|
      u.posts.each do |post|
        data << jsonize_post(post, u)
      end
    end
    render json: data
  end

private 
  def post_params
    params.require(:posts).permit(:image)
  end

  def jsonize_post(post, user)
    {
      id: post.id, 
      email: user.email.split("@").first, 
      image_url: post.image_url, 
      user_id: user.id, 
      created_at: post.created_at.strftime("%B %d, %Y")
    }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def search
	 	if params[:search]
	    @people = User.where('email LIKE ?', "#{params[:search]}%")
	  else
	    @people = User.all
	  end
  	respond_to do |format|
    format.json {render :json => @people }
		end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/pictureboard_helper.rb
module PictureboardHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/follows/create.js.erb
$("#search_user #<%= dom_id(@user)%>").fadeOut(300, function(){ 
  $("#searchResult li").remove();
  $("#follower_count").html(parseInt($("#follower_count").html()) + 1 );
  $("#followers").append("<tr id=<%= dom_id(@user) %> ><td> <%= @user.email %><br/><a class=\"btn btn-success btn-xs\" data-remote=\"true\" rel=\"nofollow\" data-method=\"delete\" href=\"/follows/<%= @user.id %>\">unsubscribe</a></td></tr>")
  get_posts();
});

app/views/follows/destroy.js.erb
$("#followers #<%= dom_id(@user)%>").fadeOut(300, function(){ 
  $(this).remove();
  $("#follower_count").html(parseInt($("#follower_count").html()) - 1 );
  get_posts();
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<%= favicon_link_tag 'paw.png', type: 'image/png' %> 
    <title>Pixigram</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
		<nav class="navbar navbar-default navbar-inverse">
			<%= link_to image_tag("paw.png", alt: "logo"), '/', class: 'navbar-brand' %>
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand" href="#"><b>Pixigram</b></a>
			</div>
	
			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="search_user">
				pe="submit" class="btn btn-default">Submit</button>
 				<% if current_user %>		
	 				<%= simple_form_for :user, url: users_search_path, remote: true, html: { class: 'navbar-form navbar-left' } do |f| %>
						<%= f.input :search, placeholder: "Search users", label: false %>
						<%#= f.submit 'Find', class: "btn btn-success"%>
		        <ul class="list-group" id="searchResult"></ul>
		        <!-- <div class="clear"></div> -->
		        <div id="userDetail"></div>
					<% end %>
				<% end %>
				<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li>
						<%= link_to('Picboard', pictureboard_index_path)  %>  
					</li>
					<li role="separator" class="divider"></li>
						<% if user_signed_in? %>
							<li>
							<%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
							</li>
						<% else %>
							<li>
							<%= link_to('Login', new_user_session_path)  %>  
							</li>
						<% end %>
				</ul>
			</li>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>	
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pictureboard/index.html.erb
<div class="dropzone">
  <%= form_for(@post, html: { multipart: true, class: "dropzone dz-clickable"}, url: posts_path) do |f|  %>
    <div class="dz-message">Drop files here or click to upload.
        <br> <span class="note">(This is just a demo dropzone. Selected files are <strong>not</strong> actually uploaded.)</span>

    </div>
    <div class="fallback">
      <%= f.file_field :image %><br>
      <%= f.submit "Upload" %>
    </div>
<% end %>
</div>
<br/>
<div class="row">
  <div class="col-md-10" id="picture_panel">
  </div>
  <div class="table-responsive col-md-2 panel panel-default" id="followers_panel">
    <table class="table table-bordered table-responsive" id="followers">
      <thead>
        <th>
          Followed
          <span class="badge badge-danger" id="follower_count">
           <%= @followed_users.count %>
          </span>
        </th>
      </thead>
      <tbody style="display: block; height: 300px; overflow: auto;">
        <% @followed_users.each do |user| %>
          <tr id="<%= dom_id(user) %>">
            <td>
              <%= user.email %><br/>
              <%= link_to "unsubscribe", follow_path(user), remote: true, method: :delete, class: "btn btn-success btn-xs unsubscribe" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/search.js.erb
<h1>Users#search</h1>
<p>Find me in app/views/users/search.html.erb</p>